library(shiny)
library(shinydashboard)
library(nlme)
source('./functions.R')
source('./models.R')
source('./monte_carlo.R')
# options(shiny.maxRequestSize=100*1024^2)
options(error = function() traceback(3))
